version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./be:/app
    environment:
      - GO_ENV=development
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
      - POSTGRES_HOST=postgres

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: