version: '3.8'

services: 
  postgres:
    image: postgres:14
    container_name: jira-db
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=another-jira-tool
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "youruser"]
      interval: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    volumes:
      - ${PWD}/be/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://youruser:yourpassword@postgres:5432/another-jira-tool?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./be:/app
    environment:
      - GO_ENV=development
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=another-jira-tool
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
    environment:
      - NODE_ENV=development

volumes:
  postgres-data:
